# Generated by Django 5.1.4 on 2024-12-18 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_rename_accounts_account'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='Accounts',
        ),
    ]
